"""Stałe używane przez integrację."""

DOMAIN = "skzp_control"
WATCHDOG_INTERVAL_SECONDS = 1
MAX_FRAME_BYTES = 64 * 1024
COMMAND_WRITE_TIMEOUT_SECONDS = 10
CONNECTION_CLOSE_TIMEOUT_SECONDS = 3

CONF_NUMBER_SEND_DELAY = "number_send_delay"
CONF_BOILER_TEMP_MAX = "boiler_temp_max"
DEFAULT_BOILER_TEMP_MAX = 80
MIN_BOILER_TEMP_MAX = 60
MAX_BOILER_TEMP_MAX = 90
CONF_COMMAND_RETRY_COUNT = "command_retry_count"
CONF_COMMAND_RETRY_DELAY = "command_retry_delay"
CONF_COMMAND_CONFIRM_TIMEOUT = "command_confirm_timeout"
CONF_NO_DATA_TIMEOUT = "no_data_timeout"
CONF_RECONNECT_DELAY = "reconnect_delay"
CONF_NOTIFY_CONNECTION_LOST = "notify_connection_lost"
CONF_NOTIFY_CONNECTION_RESTORED = "notify_connection_restored"
CONF_DISABLED_ENTITIES = "disabled_entities"
CONF_KNOWN_ENTITIES = "known_entities"
CONF_DEVICE_MODEL = "device_model"

DEFAULT_NUMBER_SEND_DELAY = 1.0
MIN_NUMBER_SEND_DELAY = 0.0
MAX_NUMBER_SEND_DELAY = 10.0

DEFAULT_COMMAND_RETRY_COUNT = 1
MIN_COMMAND_RETRY_COUNT = 0
MAX_COMMAND_RETRY_COUNT = 5

DEFAULT_COMMAND_RETRY_DELAY = 1.0
MIN_COMMAND_RETRY_DELAY = 0.0
MAX_COMMAND_RETRY_DELAY = 10.0

DEFAULT_COMMAND_CONFIRM_TIMEOUT = 5.0
MIN_COMMAND_CONFIRM_TIMEOUT = 3.0
MAX_COMMAND_CONFIRM_TIMEOUT = 30.0

DEFAULT_NO_DATA_TIMEOUT = 30.0
MIN_NO_DATA_TIMEOUT = 10.0
MAX_NO_DATA_TIMEOUT = 300.0

DEFAULT_RECONNECT_DELAY = 5.0
MIN_RECONNECT_DELAY = 1.0
MAX_RECONNECT_DELAY = 30.0

DEFAULT_NOTIFY_CONNECTION_LOST = True
DEFAULT_NOTIFY_CONNECTION_RESTORED = False
